# Generated by Django 3.2.9 on 2021-12-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('nick', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacir', models.DateTimeField()),
                ('edad', models.IntegerField()),
                ('etnia', models.IntegerField()),
                ('obeso', models.IntegerField()),
                ('hta', models.IntegerField()),
                ('dm', models.IntegerField()),
                ('tabaco', models.IntegerField()),
                ('hereda', models.IntegerField()),
                ('tactor', models.IntegerField()),
                ('psa_total', models.FloatField()),
                ('psa_estratos', models.IntegerField()),
                ('tduppre', models.IntegerField()),
                ('estadiaje_rm', models.IntegerField()),
                ('diametro_max', models.FloatField()),
                ('isup_bio', models.IntegerField()),
                ('cores_pos', models.FloatField()),
                ('nbiopsia', models.IntegerField()),
                ('histo', models.IntegerField()),
                ('gleason1a', models.IntegerField()),
                ('gleason1_pri', models.IntegerField()),
                ('gleason1_sec', models.IntegerField()),
                ('por_cil_pos', models.FloatField()),
                ('max_af_cil', models.FloatField()),
                ('bilat', models.IntegerField()),
                ('iperin', models.IntegerField()),
                ('ilinf', models.IntegerField()),
                ('ivascu', models.IntegerField()),
                ('tnm1', models.IntegerField()),
                ('isup', models.IntegerField()),
                ('fecha_prl', models.DateTimeField()),
                ('tratamiento', models.IntegerField()),
                ('gleason2a', models.IntegerField()),
                ('gleason2_pri', models.IntegerField()),
                ('gleason2_sec', models.IntegerField()),
                ('bilat2', models.IntegerField()),
                ('localiz', models.IntegerField()),
                ('multifoc', models.IntegerField()),
                ('volumen', models.FloatField()),
                ('extracap', models.IntegerField()),
                ('vvss', models.IntegerField()),
                ('iperin2', models.IntegerField()),
                ('ilinf2', models.IntegerField()),
                ('ivascu2', models.IntegerField()),
                ('pinag', models.IntegerField()),
                ('margen', models.IntegerField()),
                ('tnm2', models.IntegerField()),
                ('psapos', models.FloatField()),
                ('tdupli', models.IntegerField()),
                ('t1mtx', models.IntegerField()),
                ('fechafin', models.DateTimeField()),
                ('tsegui', models.IntegerField()),
                ('psafin', models.FloatField()),
            ],
        ),
    ]
