# Generated by Django 3.2.9 on 2022-02-14 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211207_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variables',
            name='psa_estratos',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='psa_total',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='psafin',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='psalt',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='psapos',
        ),
        migrations.CreateModel(
            name='Psa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa', models.FloatField()),
                ('fecha', models.DateField()),
                ('idPac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variables')),
            ],
        ),
    ]
