# Generated by Django 3.2.9 on 2022-03-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220217_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variables',
            old_name='hta',
            new_name='HTA',
        ),
        migrations.RenameField(
            model_name='variables',
            old_name='ilinf',
            new_name='ILINF',
        ),
        migrations.RenameField(
            model_name='variables',
            old_name='isup',
            new_name='ISUP',
        ),
        migrations.RenameField(
            model_name='variables',
            old_name='por_cil_pos',
            new_name='Por_cil_pos',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='TDDUPRE',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='TSEG',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='Ultima_revision',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='tdupli',
        ),
        migrations.AddField(
            model_name='psa',
            name='TSEG',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psa',
            name='tdupli',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variables',
            name='Fecha_Biopsia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='variables',
            name='Fecha_PRL',
            field=models.DateField(null=True),
        ),
    ]
