# Generated by Django 3.2.9 on 2022-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220309_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psa',
            name='tdupli',
            field=models.FloatField(null=True),
        ),
    ]
