# Generated by Django 3.2.9 on 2022-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_psa_tdupli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psa',
            name='TSEG',
            field=models.FloatField(null=True),
        ),
    ]
