# Generated by Django 3.2.9 on 2022-04-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_psa_tseg'),
    ]

    operations = [
        migrations.AddField(
            model_name='psa',
            name='prob_EEC',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='prob_lymph_inolved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='prob_organ_confined',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='prob_seminal_invasion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='prob_surv_10yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='prob_surv_15yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='prog_free_10yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='prog_free_5yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='Num_cil_neg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='Num_cil_pos',
            field=models.IntegerField(null=True),
        ),
    ]
