# Generated by Django 3.2.9 on 2022-04-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220412_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='psa',
            name='POST_prob_surv_15yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='POST_prog_free_10yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='POST_prog_free_5yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='POST_prog_free_7yr',
            field=models.IntegerField(null=True),
        ),
    ]
